version: '3.6'

services:
  pivxcoin:
    restart: always
    image: realnuts/docker_pivxd:4.1.1
    ports:
      - "51472:51472"
      - "51473:51473"
    volumes:
      - /opt/blockchain_data/pivx:/home/pivx/.pivx/
      - ./config/mainnet.conf:/home/pivx/.pivx/pivx.conf
