version: '3.6'

services:
  dogecoin:
    restart: always
    image: realnuts/docker_pivxd:v1.4.1.1
    ports:
      - "52472:52472"
      - "52473:52473"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/pivx_data:/pivx/data
    command:
       - "-printtoconsole"
       - "-regtest=0"
       - "-rest"
       - "-rpcallowip=0/32"
       - "-rpcallowip=172.17.0.0/16"
       - "-rpcpassword=test"
       - "-wallet=wallet1"
       - "-rpcport=52472"
       - "-rpcuser=foo"
       - "-server"
